### ISSUE TITLE
Cuman nanya

### ISSUE THREAD

**Issue by SantriInsyaf** [CiKu370/OSIF#1]
Min,jadi bikin auto report gak?#cmiiw

**Comment by CiKu370** [comment]
Waduh , auto report gk jadi ku gabungin .. Maaf ya

**Comment by andriansyah99** [comment]
Min saya boleh minta ajarin buat script nggk

**Comment by OwlxeYexlwo** [comment]
salam masta ciku and ol hekkewr , ni script masih aktiv gak ya? kok  dapet ginian mulu yaa :
[!] Can't import module 'requests'

mohon pencerahan

newbie @termux kali user
