### ISSUE TITLE
Add a option bot for send messages to friends and post in groups

### ISSUE THREAD

**Issue by Dazmed707** [CiKu370/OSIF#14]
Please Add a option bot for send messages to friends and post in groups.

**Comment by Haveyougonemad** [comment]
Lol I will be hard to see Groups and maintain them Because Groups arent just like user.something that have differnt values

**Comment by Cyb3rG0D7** [comment]
at least the option to send a specific message to all friends

**Comment by Haveyougonemad** [comment]
Create Ur Own THing

**Comment by Dazmed707** [comment]
okey
