### ISSUE TITLE
limited capacity

### ISSUE THREAD

**Issue by writingcodeandlearning** [CiKu370/OSIF#24]
Why is capacity limited to only 50?
Why the warning not to use this script too much?

**Comment by NightSling** [comment]
Please The Creator Is Down Right Now Can u screen Shot pls DOnt Ask Anything Without The ScreenShot and I can Help You So Please ScreenShot.

**Comment by writingcodeandlearning** [comment]
I can see that facebook detects suspicious activity if you use this script too much, I have removed the limit of 50 comments for this test, a few minutes later facebook blocked my account warning that it could be compromised.
