### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by fagiolonano** [CiKu370/OSIF#5]
good morning
when I try to run "python3 osif.py"  it gives me the error "inconsistent use of tabs and spaces in indentation"
File "osif.py", line 12
G = '\033[32; 1m'

I can not solve the problem
many thanks in advance

Gianni

**Comment by CiKu370** [comment]
use python 2.7.x

Pada tanggal 5 Jan 2019 11:40 PM, "fagiolonano" <notifications@github.com>
menulis:
